# -*- coding: utf-8 -*-

# Kiro Gateway
# https://github.com/jwadow/kiro-gateway
# Copyright (C) 2025 Jwadow
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""
Streaming logic for converting Kiro stream to OpenAI Responses API format.

The Responses API SSE protocol is more verbose than Chat Completions: each
logical output (reasoning / message text / function call) is wrapped in an
"item" lifecycle (added -> content parts / deltas -> done) and the stream is
bookended by `response.created` and `response.completed`.

This module implements a small state machine over the unified KiroEvent stream:
- thinking events   -> a `reasoning` item with summary text deltas
- content events    -> a `message` item with output_text deltas
- tool_use events   -> one `function_call` item each (emitted at stream end)

IMPORTANT (retry safety): `response.created` is emitted lazily, only after the
first KiroEvent arrives. parse_kiro_stream raises FirstTokenTimeoutError BEFORE
yielding anything, so on a first-token retry no events have been sent yet and
the retried attempt starts cleanly.
"""

import json
import time
from typing import TYPE_CHECKING, Any, AsyncGenerator, Callable, Awaitable, Dict, List, Optional

import httpx
from fastapi import HTTPException
from loguru import logger

from kiro.parsers import parse_bracket_tool_calls, deduplicate_tool_calls
from kiro.config import (
    FIRST_TOKEN_TIMEOUT,
    FIRST_TOKEN_MAX_RETRIES,
)
from kiro.tokenizer import count_tokens, count_message_tokens, count_tools_tokens

from kiro.streaming_core import (
    parse_kiro_stream,
    FirstTokenTimeoutError,
    calculate_tokens_from_context_usage,
    stream_with_first_token_retry as stream_with_first_token_retry_core,
)

if TYPE_CHECKING:
    from kiro.auth import KiroAuthManager
    from kiro.cache import ModelInfoCache

try:
    from kiro.debug_logger import debug_logger
except ImportError:
    debug_logger = None


__all__ = [
    "FirstTokenTimeoutError",
    "stream_kiro_to_responses",
    "stream_responses_with_first_token_retry",
    "collect_responses_response",
]


def _new_response_id() -> str:
    import uuid
    return f"resp_{uuid.uuid4().hex}"


def _new_item_id(prefix: str) -> str:
    import uuid
    return f"{prefix}_{uuid.uuid4().hex}"


def _unwrap_custom_tool_input(arguments: str) -> str:
    """
    Unwrap the freeform text of a custom tool from its synthesized JSON arguments.

    A `custom` tool is presented to the model as a JSON-schema function with a
    single `input` string field (see converters_responses._synthesize_custom_tool).
    The model therefore returns arguments like {"input": "<raw text>"}. Codex
    expects the raw text back in the `custom_tool_call.input` field, so we unwrap.

    Best-effort: if arguments are not the expected wrapped shape (malformed JSON,
    or the model emitted the payload directly), we fall back to the raw string so
    no data is lost.

    Args:
        arguments: JSON arguments string from the tool call

    Returns:
        The freeform text payload for the custom tool
    """
    from kiro.converters_responses import CUSTOM_TOOL_INPUT_KEY

    if not arguments:
        return ""
    try:
        parsed = json.loads(arguments)
    except (json.JSONDecodeError, TypeError):
        return arguments
    if isinstance(parsed, dict) and CUSTOM_TOOL_INPUT_KEY in parsed:
        value = parsed[CUSTOM_TOOL_INPUT_KEY]
        return value if isinstance(value, str) else json.dumps(value, ensure_ascii=False)
    return arguments


def _select_tool_calls(
    tool_calls: List[Dict[str, Any]],
    parallel_tool_calls: Optional[bool],
) -> List[Dict[str, Any]]:
    """Apply the Responses parallel-tool-call policy to generated calls.

    Kiro can generate multiple calls in one response and has no native switch to
    disable that behavior. When the client explicitly sets
    ``parallel_tool_calls=false``, returning only the first call serializes tool
    execution without exposing a protocol behavior the client prohibited. The
    model can request subsequent tools on later turns.

    Args:
        tool_calls: Deduplicated tool calls generated by Kiro.
        parallel_tool_calls: Responses request policy, or None when unspecified.

    Returns:
        Tool calls allowed in the current response.
    """
    if parallel_tool_calls is False and len(tool_calls) > 1:
        logger.info(
            f"Serializing {len(tool_calls)} generated tool calls because "
            "parallel_tool_calls=false; returning the first call only"
        )
        return tool_calls[:1]
    return tool_calls


class _ResponsesStreamState:
    """
    Holds counters and emit helpers for building the Responses SSE event stream.

    The main generator drives this by calling ensure_reasoning_open/
    ensure_message_open as thinking/content arrives, add_function_call for each
    tool, and finish() at the end. Every emit helper is a generator yielding SSE
    strings so the caller can `yield from` them.
    """

    def __init__(self, model: str, created_time: int):
        self.model = model
        self.created_time = created_time
        self.response_id = _new_response_id()

        self.sequence_number = 0
        self.output_index = 0

        # "reasoning" | "message" | None
        self.current_section: Optional[str] = None
        self.current_item_id: Optional[str] = None
        self.current_output_index: Optional[int] = None

        # Accumulators for the current open item
        self._text_buffer = ""
        self._reasoning_buffer = ""

        # Completed output items (for the final response object)
        self.output_items: List[Dict[str, Any]] = []

        self.created_emitted = False

    # -- low-level SSE formatting ------------------------------------------------

    def _sse(self, event_type: str, payload: Dict[str, Any]) -> str:
        payload = dict(payload)
        payload["type"] = event_type
        payload["sequence_number"] = self.sequence_number
        self.sequence_number += 1
        chunk = f"event: {event_type}\ndata: {json.dumps(payload, ensure_ascii=False)}\n\n"
        if debug_logger:
            debug_logger.log_modified_chunk(chunk.encode("utf-8"))
        return chunk

    def _response_skeleton(self, status: str, usage: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        return {
            "id": self.response_id,
            "object": "response",
            "created_at": self.created_time,
            "status": status,
            "model": self.model,
            "output": list(self.output_items),
            "usage": usage,
        }

    # -- lifecycle ---------------------------------------------------------------

    def ensure_created(self) -> AsyncGenerator[str, None]:
        async def gen():
            if self.created_emitted:
                return
            self.created_emitted = True
            yield self._sse("response.created", {"response": self._response_skeleton("in_progress")})
            yield self._sse("response.in_progress", {"response": self._response_skeleton("in_progress")})
        return gen()

    def _close_current(self) -> AsyncGenerator[str, None]:
        async def gen():
            if self.current_section == "message":
                item_id = self.current_item_id
                oidx = self.current_output_index
                yield self._sse("response.output_text.done", {
                    "item_id": item_id, "output_index": oidx,
                    "content_index": 0, "text": self._text_buffer,
                })
                yield self._sse("response.content_part.done", {
                    "item_id": item_id, "output_index": oidx, "content_index": 0,
                    "part": {"type": "output_text", "text": self._text_buffer, "annotations": []},
                })
                item = {
                    "id": item_id, "type": "message", "status": "completed", "role": "assistant",
                    "content": [{"type": "output_text", "text": self._text_buffer, "annotations": []}],
                }
                self.output_items.append(item)
                yield self._sse("response.output_item.done", {"output_index": oidx, "item": item})

            elif self.current_section == "reasoning":
                item_id = self.current_item_id
                oidx = self.current_output_index
                yield self._sse("response.reasoning_summary_text.done", {
                    "item_id": item_id, "output_index": oidx,
                    "summary_index": 0, "text": self._reasoning_buffer,
                })
                yield self._sse("response.reasoning_summary_part.done", {
                    "item_id": item_id, "output_index": oidx, "summary_index": 0,
                    "part": {"type": "summary_text", "text": self._reasoning_buffer},
                })
                item = {
                    "id": item_id, "type": "reasoning",
                    "summary": [{"type": "summary_text", "text": self._reasoning_buffer}],
                }
                self.output_items.append(item)
                yield self._sse("response.output_item.done", {"output_index": oidx, "item": item})

            self.current_section = None
            self.current_item_id = None
            self.current_output_index = None
            self._text_buffer = ""
            self._reasoning_buffer = ""
        return gen()

    def ensure_reasoning_open(self) -> AsyncGenerator[str, None]:
        async def gen():
            async for c in self.ensure_created():
                yield c
            if self.current_section == "reasoning":
                return
            async for c in self._close_current():
                yield c
            item_id = _new_item_id("rs")
            oidx = self.output_index
            self.output_index += 1
            self.current_section = "reasoning"
            self.current_item_id = item_id
            self.current_output_index = oidx
            yield self._sse("response.output_item.added", {
                "output_index": oidx,
                "item": {"id": item_id, "type": "reasoning", "summary": []},
            })
            yield self._sse("response.reasoning_summary_part.added", {
                "item_id": item_id, "output_index": oidx, "summary_index": 0,
                "part": {"type": "summary_text", "text": ""},
            })
        return gen()

    def ensure_message_open(self) -> AsyncGenerator[str, None]:
        async def gen():
            async for c in self.ensure_created():
                yield c
            if self.current_section == "message":
                return
            async for c in self._close_current():
                yield c
            item_id = _new_item_id("msg")
            oidx = self.output_index
            self.output_index += 1
            self.current_section = "message"
            self.current_item_id = item_id
            self.current_output_index = oidx
            yield self._sse("response.output_item.added", {
                "output_index": oidx,
                "item": {"id": item_id, "type": "message", "status": "in_progress",
                         "role": "assistant", "content": []},
            })
            yield self._sse("response.content_part.added", {
                "item_id": item_id, "output_index": oidx, "content_index": 0,
                "part": {"type": "output_text", "text": "", "annotations": []},
            })
        return gen()

    def add_reasoning_delta(self, text: str) -> AsyncGenerator[str, None]:
        async def gen():
            async for c in self.ensure_reasoning_open():
                yield c
            self._reasoning_buffer += text
            yield self._sse("response.reasoning_summary_text.delta", {
                "item_id": self.current_item_id, "output_index": self.current_output_index,
                "summary_index": 0, "delta": text,
            })
        return gen()

    def add_text_delta(self, text: str) -> AsyncGenerator[str, None]:
        async def gen():
            async for c in self.ensure_message_open():
                yield c
            self._text_buffer += text
            yield self._sse("response.output_text.delta", {
                "item_id": self.current_item_id, "output_index": self.current_output_index,
                "content_index": 0, "delta": text,
            })
        return gen()

    def add_function_call(self, call_id: str, name: str, arguments: str) -> AsyncGenerator[str, None]:
        async def gen():
            async for c in self.ensure_created():
                yield c
            async for c in self._close_current():
                yield c
            item_id = _new_item_id("fc")
            oidx = self.output_index
            self.output_index += 1
            call_id_final = call_id or _new_item_id("call")
            yield self._sse("response.output_item.added", {
                "output_index": oidx,
                "item": {"id": item_id, "type": "function_call", "status": "in_progress",
                         "call_id": call_id_final, "name": name, "arguments": ""},
            })
            yield self._sse("response.function_call_arguments.delta", {
                "item_id": item_id, "output_index": oidx, "delta": arguments,
            })
            yield self._sse("response.function_call_arguments.done", {
                "item_id": item_id, "output_index": oidx, "arguments": arguments,
            })
            item = {"id": item_id, "type": "function_call", "status": "completed",
                    "call_id": call_id_final, "name": name, "arguments": arguments}
            self.output_items.append(item)
            yield self._sse("response.output_item.done", {"output_index": oidx, "item": item})
        return gen()

    def add_custom_tool_call(self, call_id: str, name: str, tool_input: str) -> AsyncGenerator[str, None]:
        """
        Emit a freeform `custom_tool_call` item (e.g. Codex `exec`, `apply_patch`).

        Unlike function calls, custom tools carry raw text in `input` (not JSON
        `arguments`), and use the `response.custom_tool_call_input.*` event names.
        """
        async def gen():
            async for c in self.ensure_created():
                yield c
            async for c in self._close_current():
                yield c
            item_id = _new_item_id("ctc")
            oidx = self.output_index
            self.output_index += 1
            call_id_final = call_id or _new_item_id("call")
            yield self._sse("response.output_item.added", {
                "output_index": oidx,
                "item": {"id": item_id, "type": "custom_tool_call", "status": "in_progress",
                         "call_id": call_id_final, "name": name, "input": ""},
            })
            yield self._sse("response.custom_tool_call_input.delta", {
                "item_id": item_id, "output_index": oidx, "delta": tool_input,
            })
            yield self._sse("response.custom_tool_call_input.done", {
                "item_id": item_id, "output_index": oidx, "input": tool_input,
            })
            item = {"id": item_id, "type": "custom_tool_call", "status": "completed",
                    "call_id": call_id_final, "name": name, "input": tool_input}
            self.output_items.append(item)
            yield self._sse("response.output_item.done", {"output_index": oidx, "item": item})
        return gen()

    def finish(self, usage: Dict[str, Any], status: str = "completed") -> AsyncGenerator[str, None]:
        async def gen():
            async for c in self.ensure_created():
                yield c
            async for c in self._close_current():
                yield c
            yield self._sse("response.completed", {"response": self._response_skeleton(status, usage)})
        return gen()

    def fail(self, message: str, error_type: str = "server_error") -> AsyncGenerator[str, None]:
        """
        Emit a protocol-level terminal `response.failed` event.

        Once SSE has started the HTTP status is already 200, so an upstream error
        cannot be signalled via HTTP. Codex would otherwise see a bare connection
        drop (EOF/reset). This mints created/in_progress if not yet sent, abandons
        any incomplete item, and emits `response.failed` carrying an error object
        so the client has a clean terminal signal.
        """
        async def gen():
            async for c in self.ensure_created():
                yield c
            self.current_section = None
            self.current_item_id = None
            self.current_output_index = None
            self._text_buffer = ""
            self._reasoning_buffer = ""
            resp = self._response_skeleton("failed")
            resp["error"] = {"code": None, "message": message, "type": error_type}
            yield self._sse("response.failed", {"response": resp})
        return gen()


async def stream_kiro_to_responses_internal(
    client: httpx.AsyncClient,
    response: httpx.Response,
    model: str,
    model_cache: "ModelInfoCache",
    auth_manager: "KiroAuthManager",
    first_token_timeout: float = FIRST_TOKEN_TIMEOUT,
    request_messages: Optional[list] = None,
    request_tools: Optional[list] = None,
    custom_tool_names: Optional[set] = None,
    parallel_tool_calls: Optional[bool] = None,
) -> AsyncGenerator[str, None]:
    """
    Internal generator converting a Kiro stream to Responses API SSE events.

    Args:
        custom_tool_names: Names of tools that were freeform `custom` tools. Calls
            to these are emitted as `custom_tool_call` items (raw text input)
            instead of `function_call` items (JSON arguments).

    Raises:
        FirstTokenTimeoutError: If first token not received within timeout
    """
    custom_tool_names = custom_tool_names or set()
    state = _ResponsesStreamState(model, int(time.time()))

    full_content = ""
    full_thinking = ""
    tool_calls_from_stream: List[Dict[str, Any]] = []
    metering_data = None
    context_usage_percentage = None
    streaming_error_occurred = False

    try:
        async for event in parse_kiro_stream(response, first_token_timeout):
            if event.type == "content" and event.content:
                full_content += event.content
                async for c in state.add_text_delta(event.content):
                    yield c

            elif event.type == "thinking" and event.thinking_content:
                full_thinking += event.thinking_content
                async for c in state.add_reasoning_delta(event.thinking_content):
                    yield c

            elif event.type == "tool_use" and event.tool_use:
                tool_calls_from_stream.append(event.tool_use)

            elif event.type == "usage" and event.usage:
                metering_data = event.usage

            elif event.type == "context_usage" and event.context_usage_percentage is not None:
                context_usage_percentage = event.context_usage_percentage

        # Merge bracket-style tool calls found in the accumulated content
        bracket_tool_calls = parse_bracket_tool_calls(full_content)
        all_tool_calls = deduplicate_tool_calls(tool_calls_from_stream + bracket_tool_calls)
        all_tool_calls = _select_tool_calls(all_tool_calls, parallel_tool_calls)

        # Emit tool call items (each is a self-contained item). Freeform `custom`
        # tools become custom_tool_call items with unwrapped raw-text input; all
        # others become ordinary function_call items.
        tool_output_text = ""  # accumulate tool name + payload for token accounting
        for tc in all_tool_calls:
            func = tc.get("function") or {}
            name = func.get("name") or tc.get("name") or ""
            arguments = func.get("arguments")
            if arguments is None:
                raw_input = tc.get("input", {})
                arguments = json.dumps(raw_input, ensure_ascii=False) if raw_input else "{}"
            if not isinstance(arguments, str):
                arguments = json.dumps(arguments, ensure_ascii=False)
            if name in custom_tool_names:
                tool_input = _unwrap_custom_tool_input(arguments or "{}")
                tool_output_text += name + tool_input
                async for c in state.add_custom_tool_call(tc.get("id", ""), name, tool_input):
                    yield c
            else:
                tool_output_text += name + (arguments or "{}")
                async for c in state.add_function_call(tc.get("id", ""), name, arguments or "{}"):
                    yield c

        # Token accounting (same approach as the OpenAI path). Tool call names and
        # their generated arguments/input count toward output tokens too, otherwise
        # a pure tool-call response would report output_tokens=0.
        completion_tokens = count_tokens(full_content + full_thinking + tool_output_text)
        prompt_tokens, total_tokens, prompt_source, total_source = calculate_tokens_from_context_usage(
            context_usage_percentage, completion_tokens, model_cache, model
        )
        if prompt_source == "unknown" and request_messages:
            prompt_tokens = count_message_tokens(request_messages, apply_claude_correction=False)
            if request_tools:
                prompt_tokens += count_tools_tokens(request_tools, apply_claude_correction=False)
            total_tokens = prompt_tokens + completion_tokens

        usage = {
            "input_tokens": prompt_tokens,
            "output_tokens": completion_tokens,
            "total_tokens": total_tokens,
        }

        logger.debug(
            f"[Usage] {model}: input_tokens={prompt_tokens} ({prompt_source}), "
            f"output_tokens={completion_tokens} (tiktoken), total_tokens={total_tokens} ({total_source})"
        )

        async for c in state.finish(usage):
            yield c

    except FirstTokenTimeoutError:
        # Propagate so the retry wrapper can start a fresh attempt. No events have
        # been emitted yet (parse_kiro_stream raises before the first yield).
        raise
    except GeneratorExit:
        logger.debug("Client disconnected (GeneratorExit)")
        streaming_error_occurred = True
    except Exception as e:
        streaming_error_occurred = True
        error_type = type(e).__name__
        error_msg = str(e) if str(e) else "(empty message)"
        logger.error(f"Error during Responses streaming: [{error_type}] {error_msg}", exc_info=True)
        # SSE has already started (HTTP 200), so we cannot signal failure via HTTP.
        # Emit a protocol-level response.failed terminal event instead of letting
        # the connection drop, then end the stream gracefully (no re-raise).
        try:
            async for c in state.fail(error_msg or "Internal error during streaming"):
                yield c
        except Exception:
            pass
    finally:
        try:
            await response.aclose()
        except Exception as close_error:
            logger.debug(f"Error closing response: {close_error}")
        if streaming_error_occurred:
            logger.debug("Responses streaming completed with error")
        else:
            logger.debug("Responses streaming completed successfully")


async def stream_kiro_to_responses(
    client: httpx.AsyncClient,
    response: httpx.Response,
    model: str,
    model_cache: "ModelInfoCache",
    auth_manager: "KiroAuthManager",
    request_messages: Optional[list] = None,
    request_tools: Optional[list] = None,
    custom_tool_names: Optional[set] = None,
    parallel_tool_calls: Optional[bool] = None,
) -> AsyncGenerator[str, None]:
    """Non-retrying wrapper over stream_kiro_to_responses_internal."""
    async for chunk in stream_kiro_to_responses_internal(
        client, response, model, model_cache, auth_manager,
        request_messages=request_messages, request_tools=request_tools,
        custom_tool_names=custom_tool_names,
        parallel_tool_calls=parallel_tool_calls,
    ):
        yield chunk


async def stream_responses_with_first_token_retry(
    make_request: Callable[[], Awaitable[httpx.Response]],
    client: httpx.AsyncClient,
    model: str,
    model_cache: "ModelInfoCache",
    auth_manager: "KiroAuthManager",
    initial_response: Optional[httpx.Response] = None,
    max_retries: int = FIRST_TOKEN_MAX_RETRIES,
    first_token_timeout: float = FIRST_TOKEN_TIMEOUT,
    request_messages: Optional[list] = None,
    request_tools: Optional[list] = None,
    custom_tool_names: Optional[set] = None,
    parallel_tool_calls: Optional[bool] = None,
) -> AsyncGenerator[str, None]:
    """Streaming with automatic retry on first token timeout (Responses format)."""

    def create_http_error(status_code: int, error_text: str) -> HTTPException:
        return HTTPException(status_code=status_code, detail=f"Upstream API error: {error_text}")

    def create_timeout_error(retries: int, timeout: float) -> HTTPException:
        return HTTPException(
            status_code=504,
            detail=f"Model did not respond within {timeout}s after {retries} attempts. Please try again.",
        )

    async def stream_processor(resp: httpx.Response) -> AsyncGenerator[str, None]:
        async for chunk in stream_kiro_to_responses_internal(
            client, resp, model, model_cache, auth_manager,
            first_token_timeout=first_token_timeout,
            request_messages=request_messages, request_tools=request_tools,
            custom_tool_names=custom_tool_names,
            parallel_tool_calls=parallel_tool_calls,
        ):
            yield chunk

    try:
        async for chunk in stream_with_first_token_retry_core(
            make_request=make_request,
            stream_processor=stream_processor,
            initial_response=initial_response,
            max_retries=max_retries,
            first_token_timeout=first_token_timeout,
            on_http_error=create_http_error,
            on_all_retries_failed=create_timeout_error,
        ):
            yield chunk
    except GeneratorExit:
        raise
    except (HTTPException, httpx.HTTPError, RuntimeError, OSError) as error:
        if isinstance(error, HTTPException):
            message = str(error.detail)
        else:
            message = str(error) or type(error).__name__
        logger.error(f"Responses stream failed after retry handling: {message}")
        failure_state = _ResponsesStreamState(model, int(time.time()))
        async for chunk in failure_state.fail(message):
            yield chunk


async def collect_responses_response(
    client: httpx.AsyncClient,
    response: httpx.Response,
    model: str,
    model_cache: "ModelInfoCache",
    auth_manager: "KiroAuthManager",
    request_messages: Optional[list] = None,
    request_tools: Optional[list] = None,
    custom_tool_names: Optional[set] = None,
    parallel_tool_calls: Optional[bool] = None,
) -> dict:
    """
    Collect a full non-streaming Responses API response object.

    Consumes the Kiro stream, accumulates content/reasoning/tool calls, and
    builds the final `response` object with output items and usage.

    Args:
        custom_tool_names: Names of freeform `custom` tools. Calls to these become
            `custom_tool_call` output items (raw text input) instead of
            `function_call` items (JSON arguments).
    """
    from kiro.streaming_core import collect_stream_to_result

    custom_tool_names = custom_tool_names or set()
    result = await collect_stream_to_result(response)

    output_items: List[Dict[str, Any]] = []

    if result.thinking_content:
        output_items.append({
            "id": _new_item_id("rs"),
            "type": "reasoning",
            "summary": [{"type": "summary_text", "text": result.thinking_content}],
        })

    if result.content:
        output_items.append({
            "id": _new_item_id("msg"),
            "type": "message",
            "status": "completed",
            "role": "assistant",
            "content": [{"type": "output_text", "text": result.content, "annotations": []}],
        })

    tool_output_text = ""  # accumulate tool name + payload for token accounting
    selected_tool_calls = _select_tool_calls(result.tool_calls, parallel_tool_calls)
    for tc in selected_tool_calls:
        func = tc.get("function") or {}
        name = func.get("name") or tc.get("name") or ""
        arguments = func.get("arguments")
        if arguments is None:
            raw_input = tc.get("input", {})
            arguments = json.dumps(raw_input, ensure_ascii=False) if raw_input else "{}"
        if not isinstance(arguments, str):
            arguments = json.dumps(arguments, ensure_ascii=False)
        if name in custom_tool_names:
            tool_input = _unwrap_custom_tool_input(arguments or "{}")
            tool_output_text += name + tool_input
            output_items.append({
                "id": _new_item_id("ctc"),
                "type": "custom_tool_call",
                "status": "completed",
                "call_id": tc.get("id") or _new_item_id("call"),
                "name": name,
                "input": tool_input,
            })
        else:
            tool_output_text += name + (arguments or "{}")
            output_items.append({
                "id": _new_item_id("fc"),
                "type": "function_call",
                "status": "completed",
                "call_id": tc.get("id") or _new_item_id("call"),
                "name": name,
                "arguments": arguments or "{}",
            })

    # Tool call names + generated payloads count toward output tokens too, else a
    # pure tool-call response would report output_tokens=0.
    completion_tokens = count_tokens(result.content + result.thinking_content + tool_output_text)
    prompt_tokens, total_tokens, prompt_source, _ = calculate_tokens_from_context_usage(
        result.context_usage_percentage, completion_tokens, model_cache, model
    )
    if prompt_source == "unknown" and request_messages:
        prompt_tokens = count_message_tokens(request_messages, apply_claude_correction=False)
        if request_tools:
            prompt_tokens += count_tools_tokens(request_tools, apply_claude_correction=False)
        total_tokens = prompt_tokens + completion_tokens

    return {
        "id": _new_response_id(),
        "object": "response",
        "created_at": int(time.time()),
        "status": "completed",
        "model": model,
        "output": output_items,
        "usage": {
            "input_tokens": prompt_tokens,
            "output_tokens": completion_tokens,
            "total_tokens": total_tokens,
        },
    }
